apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sm-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sm-role
subjects:
- kind: ServiceAccount
  name: sm-service-account
  namespace: default

  # nginx ingres install, hostname